#Hide UI
hideui label,singleuser,arrows,hints,badges,safemode,hwtest,editor
showtools

#Icons
icons_dir themes/refind-theme/icons

#Background
banner themes/refind-theme/background.png
banner_scale fillscreen

#Selection
selection_small	themes/refind-theme/selection_small.png
selection_big	themes/refind-theme/selection_big.png
